# Generated by Django 4.0.5 on 2022-07-06 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
